#include "RuntimeEngine.h"
#include "EngineIdentity.h"
#include <algorithm>
#include <cmath>
#include <utility>
namespace xauusd::sovereign {
RuntimeEngine::RuntimeEngine(IBarFinalizer*f,ITimeframeStateStore*s,ShadowLedger*l) noexcept:finalizer_(f),state_store_(s),ledger_(l){}
RuntimeEngine::RuntimeEngine(IBarFinalizer*f,ITimeframeStateStore*s,ShadowLedger*l,IFeatureEngine*fe,IStructureEngine*st,IRegimeEngine*re,IEligibilityEngine*el,ISignalEngine*si,IScoreEngine*sc,IConfidenceEngine*co,IMacroContextEngine*ma,IMarketQualityEngine*mq,IRiskEngine*ri,IPortfolioRiskEngine*pr,IShadowExecutionEngine*ex,IPositionSimulator*ps,IReconciliationEngine*rc,IAuditEngine*au,HealthMonitor*hm,Watchdog*wd) noexcept
 : finalizer_(f),state_store_(s),ledger_(l),features_(fe),structure_(st),regime_(re),eligibility_(el),signal_(si),score_(sc),confidence_(co),macro_(ma),quality_(mq),risk_(ri),portfolio_risk_(pr),execution_(ex),positions_(ps),reconciliation_(rc),audit_(au),health_(hm),watchdog_(wd){}
BarFinalizationState RuntimeEngine::ingest_bar(Timeframe tf,const Bar&bar){++state_.bars_processed;if(!finalizer_)return BarFinalizationState::UNKNOWN;DataValidationResult validation{};const auto finalization=finalizer_->process_bar(tf,bar,validation);if(finalization==BarFinalizationState::FINALIZED&&state_store_)state_store_->put_state(TimeframeState(tf,bar,bar.close_time,validation.quality,finalization));touch_activity(bar.close_time);return finalization;}
bool RuntimeEngine::record_decision(const ShadowDecision&d){if(!ledger_)return false;ShadowLedgerEntry entry(d.decision_id,d.decision_time,d,{});if(!ledger_->append(entry))return false;++state_.decisions_recorded;touch_activity(d.decision_time);return true;}
RuntimeState RuntimeEngine::snapshot() const noexcept{return state_;}
const ShadowLedger& RuntimeEngine::ledger() const noexcept{static ShadowLedger empty;return ledger_?*ledger_:empty;}
void RuntimeEngine::settle_closed_position(OpenPositionRecord&record,Timestamp at){const Position&p=record.position;account_.balance+=p.net_pnl;account_.daily_pnl+=p.net_pnl;account_.equity=account_.balance;account_.peak_equity=std::max(account_.peak_equity,account_.equity);if(portfolio_risk_) {portfolio_risk_->release(record.proposal.proposal_id);const double loss_fraction=account_.balance>0.0?std::max(0.0,-account_.daily_pnl/account_.balance):1.0;portfolio_risk_->set_daily_loss_fraction(loss_fraction);}if(reconciliation_)closed_reconciliations_.push_back(reconciliation_->reconcile(record.signal,record.proposal,p));closed_positions_.push_back(p);touch_activity(at);}
void RuntimeEngine::ingest_tick(const Tick&t){latest_tick_=t;has_tick_=true;++state_.ticks_processed;std::vector<std::array<std::uint8_t,16>>to_close;for(auto&[key,record]:open_positions_){if(positions_&&positions_->update(record.position,t)&&!record.position.is_open)to_close.push_back(key);}for(const auto&key:to_close){auto it=open_positions_.find(key);if(it!=open_positions_.end()){settle_closed_position(it->second,t.event_time);open_positions_.erase(it);}}touch_activity(t.receive_time);}
DecisionFlowResult RuntimeEngine::process_bar(Timeframe tf,const Bar&bar){
 DecisionFlowResult result;if(!finalizer_||!features_||!structure_||!regime_||!eligibility_||!signal_||!score_||!confidence_||!macro_||!quality_||!risk_||!portfolio_risk_||!execution_||!positions_)return result;++state_.bars_processed;
 DataValidationResult validation{};const auto fin=finalizer_->process_bar(tf,bar,validation);result.data_valid=(fin==BarFinalizationState::FINALIZED);if(!result.data_valid)return result;if(state_store_)state_store_->put_state(TimeframeState(tf,bar,bar.close_time,validation.quality,fin));
 auto&last_f=last_features_[static_cast<int>(tf)];const FeatureSnapshot*prev_f=last_f.features.empty()?nullptr:&last_f;auto f=features_->compute(tf,bar,prev_f);if(f.data_quality==DataQualityState::OUT_OF_ORDER_QUALITY||f.data_quality==DataQualityState::INVALID_QUALITY||f.data_quality==DataQualityState::DUPLICATE_QUALITY)return result;last_f=f;
 auto st=structure_->analyze(tf,bar);if(st.data_quality==DataQualityState::OUT_OF_ORDER_QUALITY||st.data_quality==DataQualityState::INVALID_QUALITY||st.data_quality==DataQualityState::DUPLICATE_QUALITY)return result;
 auto&last_r=last_regimes_[static_cast<int>(tf)];const RegimeSnapshot*prev_r=last_r.persistence_bars==0?nullptr:&last_r;result.regime=regime_->classify(tf,f,st,prev_r);last_r=result.regime;result.eligibility=eligibility_->evaluate(result.regime,st,f);result.signal=signal_->generate(result.eligibility,result.regime,st,f);if(result.signal.direction==SignalDirection::NONE){touch_activity(bar.close_time);return result;}
 result.score=score_->compute(result.signal,result.regime,st,f);result.confidence=confidence_->compute(result.signal,result.regime,st,f);result.macro=macro_->evaluate(bar.close_time);if(macro_->blocks_signals(bar.close_time)){touch_activity(bar.close_time);return result;}
 if(has_tick_)result.quality=quality_->evaluate(latest_tick_);else {Tick synthetic(bar.close_time,bar.close_time,bar.close,bar.close,bar.close,0,0);result.quality=quality_->evaluate(synthetic);}
 portfolio_risk_->configure(limits_);result.risk=risk_->propose(result.signal,account_,limits_,symbol_spec_,result.quality);if(!portfolio_risk_->approve(result.risk))return result;
 const double bid=has_tick_?latest_tick_.bid:bar.close,ask=has_tick_?latest_tick_.ask:bar.close;result.fill=execution_->execute(result.risk,bid,ask,result.quality);if(result.fill.state!=FillState::FILLED){portfolio_risk_->release(result.risk.proposal_id);return result;}
 result.position=positions_->open(result.fill);if(!result.position.is_open){portfolio_risk_->release(result.risk.proposal_id);return result;}
 open_positions_[result.position.position_id.bytes()]=OpenPositionRecord{result.position,result.signal,result.risk};if(reconciliation_)result.reconciliation=reconciliation_->reconcile(result.signal,result.position);
 if(audit_){AuditRecord ar;ar.audit_id=detail::make_id("audit",static_cast<std::uint64_t>(bar.close_time.value()),static_cast<std::uint64_t>(AuditAction::DECISION_RECORDED),static_cast<std::uint64_t>(state_.decisions_recorded));ar.action=AuditAction::DECISION_RECORDED;ar.outcome=AuditOutcome::SUCCESS;ar.timestamp=bar.close_time;audit_->record(ar);}
 ShadowDecision decision{result.signal.decision_id,bar.close_time,tf,"TREND_CONTINUATION",Version{1},Version{1},result.signal.rationale};if(!record_decision(decision)){portfolio_risk_->release(result.risk.proposal_id);open_positions_.erase(result.position.position_id.bytes());return result;}if(health_)health_->record(HealthSnapshot{detail::make_id("runtime",1),ServiceState::ONLINE,FreshnessState::FRESH,bar.close_time,Version{1}});if(watchdog_)watchdog_->observe(bar.close_time,true,0,1024,ServiceState::ONLINE,ServiceState::ONLINE);result.completed=true;touch_activity(bar.close_time);return result;
}
void RuntimeEngine::touch_activity(Timestamp at) noexcept{state_.last_activity=at;}
} // namespace xauusd::sovereign
