#pragma once
#include <cstdint>
namespace xauusd::sovereign {
enum class CapabilityId : std::uint16_t {
    M1_FEED, M5_FEED, M15_FEED, M30_FEED, H1_FEED, H4_FEED, D1_FEED, W1_FEED, MN1_FEED,
    TICK_FEED, DATA_VALIDATION, TIMEFRAME_STATE, FEATURE_ENGINE, STRUCTURE_ENGINE, REGIME_ENGINE,
    ELIGIBILITY_ENGINE, SIGNAL_ENGINE, SCORE_ENGINE, RISK_ENGINE, SHADOW_EXECUTION, PERSISTENCE,
    RESEARCH, GUARDIAN
};
}
